Set up automating linting and formatting on file save and commit
piotrdyminski/pkd pull request #1
Opened 2022-10-06 18:59 UTC by piotrdyminski

2022-10-06 19:58 UTC, paweldyminski requested changes
Small suggestion to eslint rules, nonetheless great work!

2022-10-06 19:58 UTC, paweldyminski commented on frontend/.eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "error"
Maybe we should consider adding some other handy rules while we are at it.
What I would add just just in case are rules related to promises and unused expressions, here they are:

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.md
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unused-expressions.md

Things that are covered by them are trivial to avoid, but there is no harm to include them, just in case.

Everything besides that is looking great! 😎

2022-10-09 14:15 UTC, piotrdyminski commented on frontend/.eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "error"
`no-floating-promises` and `no-misused-promises` cover situations that rarely happen, but to use those rules properly some bloat configuration is required to be set up. I would say it's not worth it.

2022-10-09 14:17 UTC, paweldyminski commented on frontend/.eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "error"
I was mainly a suggestion anyway so it's definitely fine by me - anyway LGTM!

2022-10-09 14:18 UTC, paweldyminski approved these changes

2022-10-09 14:19 UTC, merged